### ISSUE TITLE
solver proto

### ISSUE THREAD

**Issue by lolongcovas** [HolmesShuan/ResNet-18-Caffemodel-on-ImageNet#1]
do u have the solver proto? I've tried to train resnet18 with caffe but the max acc in validation set was 50%.

**Comment by HolmesShuan** [comment]
I will upload my solver.prototxt recently.

**Comment by lolongcovas** [comment]
thank you. what about he accuracy you achieved?

**Comment by HolmesShuan** [comment]
Sorry? We just use `./build/tools/caffe train --solver models/resnet/solver.prototxt -gpu 0` to train this model on TitanX.
