### ISSUE TITLE
concerning preprocessing the data ? 

### ISSUE THREAD

**Issue by Coderx7** [HolmesShuan/ResNet-18-Caffemodel-on-ImageNet#10]
Hi, to my best knowledge Caffe only supports symmetric resizing (i.e resizing KxK (e,g 256x256)). 
How did you resize all images? Can you share your changes to Caffe or any scripts for that? 
Best Regards

**Comment by HolmesShuan** [comment]
Hi, **shrt 256** was settled **before** creating LMDB. In another word, raw data were preprocessed to 256xN(Nx256).

**Comment by Coderx7** [comment]
Thanks alot, can you also share the script by any chance?
by the way, did you run any other (fancy) preprocessings in advance? such as those implemented for inception based architectures?    
and finally how much space did those lmdb take ?

**Comment by HolmesShuan** [comment]
It has already been contained in official repo : `your-caffe-master/tools/extra/resize_crop_images.py`.
To be honest, we have not implemented other data preprocessings, yet.
It takes about 326G and 13G for training and validation dataset, respectively.

**Comment by Coderx7** [comment]
Thank you very much, I really appreciate it :)

**Comment by HolmesShuan** [comment]
:)
