### ISSUE TITLE
Why use 1x1 convolution for res2a_branch1 ?

### ISSUE THREAD

**Issue by ltqusst** [HolmesShuan/ResNet-18-Caffemodel-on-ImageNet#11]
According to ResNet Paper, in Resnet18/34 cases, for res2a_branch1, direct connection is used instead of 1x1 convolution, why are you using 1x1 convolution ?, Is it necessary?

**Comment by HolmesShuan** [comment]
From our point of view, it won't be necessary. Compared with the learning rate and batch-size, this difference should be almost no contribution to the final accuracy.
