### ISSUE TITLE
Predictions are wrong

### ISSUE THREAD

**Issue by Tez01** [HolmesShuan/ResNet-18-Caffemodel-on-ImageNet#13]
Hi,
I used your pre-trained model for inference but the results are very odd. None of the top 5 class are matching the actual labels. 
Is there any kind of preprocessing that you implemented?

**Comment by HolmesShuan** [comment]
Just
```python
transform_param {
        mirror: true
        crop_size: 224
        mean_value: 104
        mean_value: 117
        mean_value: 123
    }
```
, nothing new.

**Comment by Tez01** [comment]
Scale values?

**Comment by HolmesShuan** [comment]
1

**Comment by Tez01** [comment]
Ok Thanks.

**Comment by HolmesShuan** [comment]
I will keep this issue open until someone solves it. Sorry for any inconvenience.
