### ISSUE TITLE
Failed to parse NetParameter file: ResNet-18-model.caffemodel

### ISSUE THREAD

**Issue by PearlDzzz** [HolmesShuan/ResNet-18-Caffemodel-on-ImageNet#3]
F0420 14:02:31.106763 3624 upgrade_proto.cpp:86] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ResNet-18-model.caffemodel
***Check failure stack trace: ***

**Comment by HolmesShuan** [comment]
`More crash messages` will help a lot. From details given above, I guess .prototxt and .caffemodel mismatch may cause this problem.

**Comment by cristina510** [comment]
Hi,@ChristineRYY, I  also came cross the problem recently. Could you please give me some advice? Any reply would be highly appreciated~


Problem has been solved. The caffemodel is not correctly downloaded.Thanks:) @HolmesShuan
