### ISSUE TITLE
Test Accuracy

### ISSUE THREAD

**Issue by marvis** [HolmesShuan/ResNet-18-Caffemodel-on-ImageNet#5]
Hi HolmesShuan,

Thanks for your model!
I just test your model on ImageNet with only one center crop. The top1 accuracy is 53.136% and  top5 78.124?
Is it correct? How do you test your model?

Best,

**Comment by HolmesShuan** [comment]
I have tested this model on ILSVRC12 Validation Set(**short 256**), also resnet-50,152 provided by [He](https://github.com/KaimingHe/deep-residual-networks) have been tested on this lmdb set to make sure our validation set is correct.
