### ISSUE TITLE
Check failed: target_blobs.size() == source_layer.blobs_size() (2 vs. 1) Incompatible number of blobs for layer conv1

### ISSUE THREAD

**Issue by mingqizhang** [HolmesShuan/ResNet-18-Caffemodel-on-ImageNet#6]
When i finetune the Resnet18 from the pre-model,there has a problem:
Check failed: target_blobs.size() == source_layer.blobs_size() (2 vs. 1) Incompatible number of blobs for layer conv1
and i add the bias_term,it can not solve it,so how to do?

**Comment by HolmesShuan** [comment]
`bias_term: false` in `conv1`.
